[package]
name = "polyanya"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
stats = []
verbose = []

[dependencies]
tracing = { version = "0.1", optional = true }
hashbrown = { version = "0.12" }
glam = { version = "0.21.3", features = ["approx"] }

[dev-dependencies]
criterion = "0.3"
tracing-tracy = "0.10"
tracing-subscriber = "0.3"
tracing = "0.1"


[[bench]]
name = "path"
harness = false
